In [1]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf

tf.enable_eager_execution()

In [2]:
#tensor的计算
#tensor本身也是一种数据类型，其数据类型包括了 
#array，vector, matrix等全部的和线性代数有关的数学量
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
#.add的功能是，tensor对应项分别相加。
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
#tensor也包含科学计算，累加，平方，log等

print(tf.encode_base64("hello world"))
#把string转化成base64的格式

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [18]:
x = tf.matmul([[1]],  [[2, 3]])
#matrix multiply
print(x.shape)
print(x.dtype)#dtype是内部存储数据的类型

(1, 2)
<dtype: 'int32'>


In [15]:
import numpy as np
s=np.array([[1]])  #二维的array
w=np.array([1])    #一维的array

In [14]:
s.shape
#对于numpy而言，嵌套几层（同级别的算一层）括号就是几维

(1, 1)

### Tensor和Numpy之间的转换

In [19]:
import numpy as np
ndarray=np.ones([3,3])#3*3的二维np矩阵

In [20]:
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ndarray.shape

(3, 3)

In [25]:
#print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor=tf.multiply(ndarray,42)
print(tensor)
#在tensor里面,我们可以直接把numpy数据作为tf的输入，
#而tf会把其自动转换会tensor，结果也是tensor的格式。
print(tensor+1)
print(np.add(tensor,1))
#numpy.add()可以对矩阵和矩阵(对应元素的相加），array和array，矩阵对scalar，
#任意配对
#如果我们直接对tensor相加，结果仍然是tensor
#如果我们用np.add（）相加，结果就是numpy


tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]], shape=(3, 3), dtype=float64)


In [31]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False
