## keras.concatenate的用法
即让tensor在对应维度上相加的一种方法。

In [32]:
import numpy as np
import keras.backend as K
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=np.array([[[[1, 2,9], [2, 3,9]], [[4, 4,9], [5, 3,9]]],[[[11, 12,9], [12, 13,9]], [[14, 4,9], [15, 13,9]]]])
print(a)
a.shape


[[[[ 1  2  9]
   [ 2  3  9]]

  [[ 4  4  9]
   [ 5  3  9]]]


 [[[11 12  9]
   [12 13  9]]

  [[14  4  9]
   [15 13  9]]]]


(2, 2, 2, 3)

In [28]:
b=np.array([[[[7, 4,9], [8, 4,9]], [[2, 10,9], [15, 11,9]]],[[[17, 14,9], [18, 14,9]], [[12, 10,9], [115, 111,9]]]])
print( b)

[[[[  7   4   9]
   [  8   4   9]]

  [[  2  10   9]
   [ 15  11   9]]]


 [[[ 17  14   9]
   [ 18  14   9]]

  [[ 12  10   9]
   [115 111   9]]]]


In [36]:

t1 = K.variable(a)
t2 = K.variable(b)
d0 = K.concatenate([t1 , t2] , axis=0)
d1 = K.concatenate([t1 , t2] , axis=1)
d2 = K.concatenate([t1 , t2] , axis=2)
d3 = K.concatenate([t1 , t2] , axis=3)
 
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    print("axis = 0\n",sess.run(d0))
    print(sess.run(d0).shape)
    print("\n\n\n")
    print("axis = 1\n",sess.run(d1))
    print(sess.run(d1).shape)
    print("\n\n\n")
    print("axis = 2\n",sess.run(d2))
    print(sess.run(d2).shape)
    print("\n\n\n")
    print("axis = 3\n",sess.run(d3))
    print(sess.run(d3).shape)



axis = 0
 [[[[  1.   2.   9.]
   [  2.   3.   9.]]

  [[  4.   4.   9.]
   [  5.   3.   9.]]]


 [[[ 11.  12.   9.]
   [ 12.  13.   9.]]

  [[ 14.   4.   9.]
   [ 15.  13.   9.]]]


 [[[  7.   4.   9.]
   [  8.   4.   9.]]

  [[  2.  10.   9.]
   [ 15.  11.   9.]]]


 [[[ 17.  14.   9.]
   [ 18.  14.   9.]]

  [[ 12.  10.   9.]
   [115. 111.   9.]]]]
(4, 2, 2, 3)




axis = 1
 [[[[  1.   2.   9.]
   [  2.   3.   9.]]

  [[  4.   4.   9.]
   [  5.   3.   9.]]

  [[  7.   4.   9.]
   [  8.   4.   9.]]

  [[  2.  10.   9.]
   [ 15.  11.   9.]]]


 [[[ 11.  12.   9.]
   [ 12.  13.   9.]]

  [[ 14.   4.   9.]
   [ 15.  13.   9.]]

  [[ 17.  14.   9.]
   [ 18.  14.   9.]]

  [[ 12.  10.   9.]
   [115. 111.   9.]]]]
(2, 4, 2, 3)




axis = 2
 [[[[  1.   2.   9.]
   [  2.   3.   9.]
   [  7.   4.   9.]
   [  8.   4.   9.]]

  [[  4.   4.   9.]
   [  5.   3.   9.]
   [  2.  10.   9.]
   [ 15.  11.   9.]]]


 [[[ 11.  12.   9.]
   [ 12.  13.   9.]
   [ 17.  14.   9.]
   [ 18.  14.   9.]]

  [[ 1

In [20]:
t1 = K.variable(np.array([[[[1, 2], [2, 3]], [[4, 4], [5, 3]]],[[[11, 12], [12, 13]], [[14, 4], [15, 13]]]]))
t2 = K.variable(np.array([[[[7, 4], [8, 4]], [[2, 10], [15, 11]]],[[[17, 14], [18, 14]], [[12, 10], [115, 111]]]]))
d0 = K.concatenate([t1 , t2] , axis=-2)
d1 = K.concatenate([t1 , t2] , axis=1)
d2 = K.concatenate([t1 , t2] , axis=3)
d3 = K.concatenate([t1 , t2] , axis=2)
 
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    print("axis = 1\n",sess.run(d1))
    print("axis = 2\n",sess.run(d3))
    print("axis = 3\n",sess.run(d2))
    

axis = 1
 [[[[  1.   2.]
   [  2.   3.]]

  [[  4.   4.]
   [  5.   3.]]

  [[  7.   4.]
   [  8.   4.]]

  [[  2.  10.]
   [ 15.  11.]]]


 [[[ 11.  12.]
   [ 12.  13.]]

  [[ 14.   4.]
   [ 15.  13.]]

  [[ 17.  14.]
   [ 18.  14.]]

  [[ 12.  10.]
   [115. 111.]]]]
axis = 2
 [[[[  1.   2.]
   [  2.   3.]
   [  7.   4.]
   [  8.   4.]]

  [[  4.   4.]
   [  5.   3.]
   [  2.  10.]
   [ 15.  11.]]]


 [[[ 11.  12.]
   [ 12.  13.]
   [ 17.  14.]
   [ 18.  14.]]

  [[ 14.   4.]
   [ 15.  13.]
   [ 12.  10.]
   [115. 111.]]]]
axis = 3
 [[[[  1.   2.   7.   4.]
   [  2.   3.   8.   4.]]

  [[  4.   4.   2.  10.]
   [  5.   3.  15.  11.]]]


 [[[ 11.  12.  17.  14.]
   [ 12.  13.  18.  14.]]

  [[ 14.   4.  12.  10.]
   [ 15.  13. 115. 111.]]]]


每个矩阵中，相应的维度看成一个整体拿出来，合并为一个更长的维度。
因此我们可以把concatente 看成在相应维度上的加长！！！。即 （2，3，4，5） 和（2，5，4，5）如果在第一维度上串联，那么得到的一定是（2，3+5，4，5）的维度上的向量。